import { env } from "@/lib/env";
import { SITE } from "@/content/site";
import type { Show, Winner } from "@/lib/queries";

/**
 * Structured data and social-card primitives.
 *
 * Two rules run through this file, and both are refusals rather than features:
 *
 *   1. A schema is never satisfied by inventing a fact. `Event` requires
 *      `startDate`, and `Show.startsAt` is deliberately null because the old
 *      site says August 11 in one place and August 28 in another. So
 *      `showEventJsonLd` returns null. Invalid Event markup is penalised by
 *      Google; a guessed date would be worse than either.
 *
 *   2. Every URL emitted here points at something that exists. The old site's
 *      og:image is `https://deanslist.live/` — an HTML document served as an
 *      image — which is the single reason its share previews never render
 *      (docs/SITE-AUDIT.md §4). Nothing below references a path that has not
 *      been checked into the repository or generated by a route.
 *
 * Nothing here reads the database. Callers pass rows they already loaded
 * through @/lib/queries, so a page never pays for a second round trip to add
 * its structured data.
 */

/* ------------------------------------------------------------------- urls */

const SITE_URL = env.NEXT_PUBLIC_SITE_URL.replace(/\/+$/, "");

/** Absolute URL for a site-relative path. Passes through anything already absolute. */
export function absoluteUrl(path = "/"): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith("/") ? "" : "/"}${path}`;
}

/**
 * Stable node id for the publisher. Every other node references this instead of
 * repeating the organisation inline, so a crawler resolves one entity across the
 * whole site rather than a new one per page.
 */
const ORGANIZATION_ID = `${SITE_URL}/#organization`;

/* ------------------------------------------------------------------ types */

export type JsonLd = Record<string, unknown>;

export type Crumb = { name: string; path: string };

/* --------------------------------------------------------------- rendering */

/**
 * Props for the `<script>` tag that carries a JSON-LD node.
 *
 *   <script {...jsonLdScriptProps(organizationJsonLd())} />
 *
 * The escaping is not decorative. Show descriptions and winner stories are
 * editable from the admin dashboard, and a value containing `</script>` would
 * otherwise close the tag and let the rest of the string run as markup. Escaping
 * `<`, `>` and `&` as unicode sequences keeps the JSON valid and inert.
 * U+2028 and U+2029 are legal in JSON but not in a JavaScript string literal,
 * so they are escaped too.
 */
export function jsonLdScriptProps(data: JsonLd) {
  const json = JSON.stringify(data)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");

  return {
    type: "application/ld+json" as const,
    dangerouslySetInnerHTML: { __html: json },
  };
}

/**
 * Combine several nodes into one `@graph` document, dropping any that declined
 * to render. Returns null when nothing survived, so a page can write:
 *
 *   const ld = jsonLdGraph(breadcrumbJsonLd(trail), showEventJsonLd(show));
 *   {ld && <script {...jsonLdScriptProps(ld)} />}
 *
 * and never emit an empty script tag.
 */
export function jsonLdGraph(...nodes: (JsonLd | null | undefined)[]): JsonLd | null {
  const graph = nodes.filter((n): n is JsonLd => Boolean(n)).map(stripContext);
  if (graph.length === 0) return null;
  return { "@context": "https://schema.org", "@graph": graph };
}

/** `@context` belongs on the document, not on each node inside a `@graph`. */
function stripContext(node: JsonLd): JsonLd {
  if (!("@context" in node)) return node;
  const { "@context": _context, ...rest } = node;
  return rest;
}

/* ---------------------------------------------------------- organization */

/**
 * The publisher. `sameAs` carries only the two profiles verified as live in
 * docs/SITE-AUDIT.md — the old footer links several more that are dead, and
 * pointing a search engine at a 404 to look busy is worse than listing two.
 */
export function organizationJsonLd(): JsonLd {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": ORGANIZATION_ID,
    name: SITE.name,
    legalName: SITE.legalName,
    url: absoluteUrl("/"),
    // src/app/icon.png, generated by scripts/make-og-image.mjs and committed.
    logo: absoluteUrl("/icon.png"),
    image: absoluteUrl("/og.jpg"),
    description: SITE.description,
    slogan: SITE.tagline,
    email: SITE.email,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Charleston",
      addressRegion: "WV",
      addressCountry: "US",
    },
    sameAs: [SITE.socials.youtube, SITE.socials.facebook],
  };
}

/* ------------------------------------------------------------------ event */

/**
 * `Event` for a show — or null.
 *
 * Google's Event rich result requires `name` and `startDate`, and treats a
 * missing or malformed date as invalid markup rather than as partial data.
 * `Show.startsAt` is null on purpose for both current shows: the old homepage
 * announces August 11 while its own winner story is dated August 28, so no
 * date on that site can be published as fact (docs/SITE-AUDIT.md §7).
 *
 * `entryDeadline` is deliberately NOT substituted. The date entries close is
 * not the date the show starts, and quietly mapping one to the other to satisfy
 * a validator would put a wrong date in front of every search result — the exact
 * failure mode this project exists to clean up.
 *
 * So: no confirmed start date, no Event node. The page still carries its
 * breadcrumb and the site-wide Organization. Once the client confirms a date and
 * it lands on `Show.startsAt`, this starts emitting with no code change.
 */
export function showEventJsonLd(show: Show): JsonLd | null {
  const startDate = isoDate(show.startsAt);
  if (!startDate) return null;

  const node: JsonLd = {
    "@context": "https://schema.org",
    "@type": "Event",
    name: show.title,
    startDate,
    url: absoluteUrl(`/shows/${show.slug}`),
    image: absoluteUrl(showImagePath(show)),
    // The show is broadcast, never ticketed at a venue, so the attendance mode
    // and a VirtualLocation are the accurate shape here. The URL is the live
    // channel, which is where an attendee actually goes.
    eventAttendanceMode: "https://schema.org/OnlineEventAttendanceMode",
    location: {
      "@type": "VirtualLocation",
      url: SITE.socials.youtube,
    },
    organizer: { "@id": ORGANIZATION_ID },
    performer: { "@id": ORGANIZATION_ID },
  };

  const description = show.tagline ?? show.description;
  if (description) node.description = description;

  // Only two statuses can be asserted from a start date alone. A CLOSED season
  // is not "cancelled" or "postponed", so nothing is claimed for it.
  if (show.status === "OPEN" || show.status === "LIVE") {
    node.eventStatus = "https://schema.org/EventScheduled";
  }

  return node;
}

/* ----------------------------------------------------------------- person */

/**
 * `Person` for a winner.
 *
 * Note the identity risk this inherits rather than creates: the old homepage
 * and the old winners page name two different people as the first Crown the
 * Sound champion. `src/content/site.ts` carries one of them forward on the
 * client's instruction and flags it unconfirmed. Structured data mirrors
 * whatever the page already states, so this will publish that name to search
 * engines in machine-readable form. It should not go live before the client
 * confirms — see docs/PROJECT-BRIEF.md §8.
 *
 * `image` is omitted when there is no photograph. The old winner page carries
 * only the site logo, and captioning a logo — or a gallery shot of an
 * unidentified person — as this individual's likeness is not a trade worth
 * making for a thumbnail.
 */
export function winnerPersonJsonLd(winner: Winner): JsonLd {
  const node: JsonLd = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: winner.name,
    url: absoluteUrl(`/winners/${winner.slug}`),
  };

  if (winner.story) node.description = winner.story;
  if (winner.photoUrl) node.image = absoluteUrl(winner.photoUrl);
  if (winner.showTitle) {
    node.award = `${winner.showTitle} winner`;
    node.subjectOf = {
      "@type": "CreativeWork",
      name: winner.showTitle,
      publisher: { "@id": ORGANIZATION_ID },
    };
  }

  return node;
}

/* ------------------------------------------------------------- breadcrumb */

/**
 * `BreadcrumbList` from the trail a page already knows about. Pass the full
 * path including the home entry:
 *
 *   breadcrumbJsonLd([
 *     { name: "Home", path: "/" },
 *     { name: "Shows", path: "/shows" },
 *     { name: show.title, path: `/shows/${show.slug}` },
 *   ])
 */
export function breadcrumbJsonLd(trail: Crumb[]): JsonLd | null {
  if (trail.length === 0) return null;

  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

/* ------------------------------------------------------- open graph cards */

/** next/og card dimensions. The size every social platform crops from. */
export const OG_SIZE = { width: 1200, height: 630 } as const;

export const OG_CONTENT_TYPE = "image/png";

/**
 * The card palette, lifted from tailwind.config.ts rather than picked again.
 *
 * Satori cannot read Tailwind classes, so an OG route has to name colours as
 * hex. Sourcing them here means there is still one place they are defined, and
 * a token change does not silently leave the share cards on last season's
 * palette. Do not add a value to this object that is not already a token.
 */
export const OG = {
  ink: "#0A0A0C", // ink.DEFAULT
  line: "#2A2A34", // ink.line
  gold: "#D4AF37", // gold.DEFAULT
  goldLight: "#F7ECC6", // gold.light
  goldDeep: "#7A5E14", // gold.shadow
  chalk: "#FFFFFF", // chalk.DEFAULT
  chalkBody: "rgba(255,255,255,0.72)", // chalk.body
  chalkMuted: "rgba(255,255,255,0.50)", // chalk.muted
  redLive: "#FF2D42", // brandred.live — urgency only, never decoration
} as const;

/**
 * The gold rule that runs along the bottom edge of every card. Two specular
 * stops and a hue drift, which is what makes gold read as metal instead of as
 * mustard — the same reasoning as `bg-gold-metal`, written out because satori
 * only understands plain CSS gradients.
 */
export const OG_GOLD_BAR =
  `linear-gradient(90deg, ${OG.goldDeep} 0%, ${OG.gold} 26%, ${OG.goldLight} 50%, ${OG.gold} 74%, ${OG.goldDeep} 100%)`;

/**
 * Title size for a 1200px card, chosen from the length of the string.
 *
 * A fixed size either shrinks "PJ Galloway" to nothing or pushes a long show
 * title off the canvas, and satori has no text-fitting of its own. The steps are
 * measured against the widest realistic string at each bound.
 *
 * Character count is an approximation and will always be one: "THE DEAN'S LIST"
 * and "CROWN THE SOUND" are both fifteen characters and the second is 12% wider,
 * because W and O are. The bands are set low enough that a wide string wraps to
 * two lines instead of overflowing — the card layout handles a second line, it
 * cannot handle a title running off the edge.
 */
export function ogTitleSize(text: string): number {
  const n = text.trim().length;
  if (n <= 12) return 128;
  if (n <= 16) return 100;
  if (n <= 24) return 84;
  if (n <= 36) return 68;
  if (n <= 52) return 54;
  return 46;
}

/**
 * Image to represent a show. Prefers artwork that is already a real image file;
 * otherwise the show's own generated OG card, which is always a 1200x630 PNG.
 *
 * The extension test matters: media paths in src/content/site.ts are stored
 * without one ("/media/shows/drop-that-mike-key-art") because the app picks
 * avif/webp/jpg per browser at render time. A crawler does no such negotiation,
 * so an extensionless path would be another broken og:image.
 */
function showImagePath(show: Show): string {
  const art = show.keyArt ?? show.heroPoster;
  if (art && /\.(avif|webp|jpe?g|png|gif)$/i.test(art)) return art;
  return `/shows/${show.slug}/opengraph-image`;
}

/* ---------------------------------------------------------------- helpers */

/** A valid date string, or null. Guards against a bad value reaching a schema. */
function isoDate(value: string | null): string | null {
  if (!value) return null;
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
}
