/**
 * Host the site's media on Cloudinary.
 *
 *   node scripts/upload-media.mjs --test    # confirm the credentials work
 *   node scripts/upload-media.mjs           # upload
 *   node scripts/upload-media.mjs --check   # verify every URL the app requests
 *   node scripts/upload-media.mjs --purge   # delete everything under deanslist/
 *
 * Reads CLOUDINARY_URL from .env:
 *   CLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<cloud_name>
 *
 * The key and secret are used ONLY here. Delivery needs nothing but the cloud
 * name, which is public — see src/lib/media.ts and docs/CLOUDINARY-SETUP.md.
 *
 * Requests are signed by hand rather than pulling in the Cloudinary SDK: this
 * runs a handful of times, and a dependency that exists to build one SHA-1
 * string should not ship in production installs.
 *
 * WHAT GETS UPLOADED, AND WHY IT IS NOT EVERYTHING
 *
 * Only source files: the .jpg/.png for images, the .mp4 for video. Cloudinary
 * addresses an asset as public_id + requested format, so it derives .avif,
 * .webp and .webm from those sources on demand — verified, not assumed.
 * Uploading the local variants as well would put the extension inside the
 * public_id and produce doubled URLs like cts-01.jpg.jpg. 49 files instead of
 * 164, and the URLs the app already builds work untouched.
 *
 * A video's poster frame is an image resource, not a video one, so it uploads
 * as an image and BackgroundVideo resolves it through mediaImage().
 */

import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import { join, relative, extname } from "node:path";

const PUBLIC = "public";
const ROOT = "public/media";
const FOLDER = "deanslist";

/* ------------------------------------------------------------------ config */

// .env is not loaded automatically in a bare node script.
async function loadEnv() {
  try {
    const txt = await readFile(".env", "utf8");
    for (const line of txt.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
      if (m && !process.env[m[1]]) {
        process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
      }
    }
  } catch {
    /* absent .env is fine if the variable is already exported */
  }
}

await loadEnv();

const url = process.env.CLOUDINARY_URL;
if (!url) {
  console.error(
    [
      "",
      "CLOUDINARY_URL is not set.",
      "",
      "Add this line to .env (it is gitignored, so it never reaches GitHub):",
      "",
      "  CLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<cloud_name>",
      "",
      "See docs/CLOUDINARY-SETUP.md.",
      "",
    ].join("\n"),
  );
  process.exit(1);
}

const parsed = url.match(/^cloudinary:\/\/([^:]+):([^@]+)@(.+)$/);
if (!parsed) {
  console.error("CLOUDINARY_URL is malformed. Expected cloudinary://key:secret@cloud_name");
  process.exit(1);
}
const [, API_KEY, API_SECRET, CLOUD] = parsed;

const TEST_ONLY = process.argv.includes("--test");
const CHECK_ONLY = process.argv.includes("--check");
const PURGE = process.argv.includes("--purge");

/* ----------------------------------------------------------------- helpers */

/** Uploaded as-is. */
const IMAGE_SOURCE = new Set([".jpg", ".jpeg", ".png"]);
const VIDEO_SOURCE = new Set([".mp4"]);
/** Generated by Cloudinary from the sources above. Never uploaded. */
const DERIVED_IMAGE = [".avif", ".webp"];
const DERIVED_VIDEO = [".webm"];

const mb = (n) => (n / 1024 / 1024).toFixed(2) + " MB";
const BASIC = Buffer.from(`${API_KEY}:${API_SECRET}`).toString("base64");

function kindOf(file) {
  const e = extname(file).toLowerCase();
  if (VIDEO_SOURCE.has(e)) return "video";
  if (IMAGE_SOURCE.has(e)) return "image";
  return null;
}

/**
 * Public id, taken relative to public/ rather than public/media so it keeps the
 * leading "media/" segment.
 *
 * The app asks for "/media/brand/logo" and the delivery base ends at the folder,
 * so the stored id has to be "deanslist/media/brand/logo" for the two to meet.
 * Dropping the segment produced a whole set of 404s that looked like a Cloudinary
 * problem and was really an off-by-one-path-segment.
 */
function idOf(file) {
  return relative(PUBLIC, file).split(/[\\/]+/).join("/").replace(/\.[^.]+$/, "");
}

/** Upload API signature: alphabetically sorted params, then the secret appended. */
function sign(params) {
  const toSign = Object.keys(params)
    .filter((k) => params[k] !== undefined && params[k] !== "")
    .sort()
    .map((k) => `${k}=${params[k]}`)
    .join("&");
  return createHash("sha1").update(toSign + API_SECRET).digest("hex");
}

async function walk(dir, acc = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) await walk(p, acc);
    else acc.push(p);
  }
  return acc;
}

const deliveryUrl = (id, kind, ext) =>
  `https://res.cloudinary.com/${CLOUD}/${kind}/upload/${FOLDER}/${id}${ext}`;

async function upload(file) {
  const kind = kindOf(file);
  const id = idOf(file);
  if (!kind) return { id, skipped: true };

  const params = {
    public_id: `${FOLDER}/${id}`,
    timestamp: Math.floor(Date.now() / 1000),
    overwrite: "true",
    invalidate: "true",
    unique_filename: "false",
    use_filename: "false",
  };

  const form = new FormData();
  for (const [k, v] of Object.entries(params)) form.append(k, String(v));
  form.append("api_key", API_KEY);
  form.append("signature", sign(params));
  form.append("file", new Blob([await readFile(file)]), `${id.split("/").pop()}${extname(file)}`);

  const res = await fetch(`https://api.cloudinary.com/v1_1/${CLOUD}/${kind}/upload`, {
    method: "POST",
    body: form,
  });

  const body = await res.json().catch(() => ({}));
  if (!res.ok) return { id, error: body?.error?.message ?? `HTTP ${res.status}` };
  return { id, kind, bytes: body.bytes ?? 0 };
}

/* -------------------------------------------------------------- credentials */

/**
 * Cloudinary has two auth mechanisms and they are NOT interchangeable:
 *   Upload API (/v1_1/<cloud>/image/upload)  -> signed params
 *   Admin API  (/v1_1/<cloud>/resources/...) -> HTTP Basic auth
 * Signing an Admin call returns 401 with perfectly valid credentials, which is
 * a confusing way to fail. Checking here means a typo in .env surfaces once
 * rather than as 49 identical upload failures.
 */
if (TEST_ONLY) {
  const res = await fetch(
    `https://api.cloudinary.com/v1_1/${CLOUD}/resources/image?max_results=1`,
    { headers: { Authorization: `Basic ${BASIC}` } },
  );

  if (res.ok) {
    console.log("credentials OK");
    console.log(`  cloud name : ${CLOUD}`);
    console.log(`  api key    : ${API_KEY}`);
    console.log(`  api secret : ${"*".repeat(API_SECRET.length)} (${API_SECRET.length} chars)`);
    console.log("\nReady. Run: node scripts/upload-media.mjs");
  } else {
    const body = await res.text();
    console.error(`credentials REJECTED (HTTP ${res.status})`);
    if (res.status === 401) {
      console.error("\nThe api_key or api_secret is wrong, or they come from different");
      console.error("key pairs. This account has more than one key — check the secret");
      console.error(`you revealed belongs to key ${API_KEY} and not another row.`);
    } else if (res.status === 404) {
      console.error(`\nCloud name "${CLOUD}" not found. It is the part after the @.`);
    }
    console.error(`\n${body.slice(0, 300)}`);
    process.exitCode = 1;
  }
  // No process.exit(): calling it while a fetch handle is still closing trips a
  // libuv assertion on Windows. Letting the event loop drain is clean.
}

/* ------------------------------------------------------------------- purge */

if (PURGE) {
  let removed = 0;
  for (const kind of ["image", "video"]) {
    // delete_all is capped per call, so loop until the prefix is empty.
    for (let pass = 0; pass < 20; pass++) {
      const res = await fetch(
        `https://api.cloudinary.com/v1_1/${CLOUD}/resources/${kind}/upload?prefix=${FOLDER}/`,
        { method: "DELETE", headers: { Authorization: `Basic ${BASIC}` } },
      );
      const body = await res.json().catch(() => ({}));
      const n = Object.keys(body.deleted ?? {}).length;
      removed += n;
      if (!res.ok) {
        console.error(`  purge ${kind} failed: ${body?.error?.message ?? res.status}`);
        break;
      }
      if (n === 0 || !body.partial) break;
    }
  }
  console.log(`purged ${removed} assets from ${FOLDER}/`);
}

/* --------------------------------------------------------------------- run */

if (!TEST_ONLY && !PURGE) {
  const all = await walk(ROOT).catch(() => []);
  if (!all.length) {
    console.error(`Nothing in ${ROOT}. Run the harvest and optimise scripts first.`);
    process.exit(1);
  }

  const sources = all.filter(kindOf);
  const images = sources.filter((f) => kindOf(f) === "image");
  const videos = sources.filter((f) => kindOf(f) === "video");
  const bytes = (await Promise.all(sources.map(async (f) => (await stat(f)).size))).reduce(
    (a, b) => a + b,
    0,
  );

  console.log(`cloud    ${CLOUD}`);
  console.log(`folder   ${FOLDER}/`);
  console.log(
    `sources  ${images.length} images + ${videos.length} videos = ${mb(bytes)}` +
      `  (${all.length - sources.length} derived formats left for Cloudinary)\n`,
  );

  if (CHECK_ONLY) {
    // Checks every URL the app actually requests, including the derived
    // formats — the ones most likely to be wrong. Delivery is public, so this
    // needs no credentials at all.
    const targets = [];
    for (const f of sources) {
      const kind = kindOf(f);
      const id = idOf(f);
      const exts =
        kind === "image"
          ? [extname(f).toLowerCase(), ...DERIVED_IMAGE]
          : [extname(f).toLowerCase(), ...DERIVED_VIDEO];
      for (const ext of exts) targets.push({ id, kind, ext });
    }

    let ok = 0;
    const missing = [];
    for (const t of targets) {
      const res = await fetch(deliveryUrl(t.id, t.kind, t.ext), { method: "HEAD" });
      if (res.ok) ok++;
      else missing.push(`${t.kind} ${t.id}${t.ext} (HTTP ${res.status})`);
    }

    console.log(`${ok} of ${targets.length} URLs delivering`);
    if (missing.length) {
      console.log("\nmissing:");
      for (const m of missing) console.log(`  ${m}`);
      process.exitCode = 1;
    }
  } else {
    let done = 0;
    let sent = 0;
    const failures = [];

    // Serial. A free-tier account rate limits, and a half-uploaded set is worse
    // than a slow one.
    for (const f of sources) {
      const r = await upload(f);
      if (r.error) failures.push(`${r.id}: ${r.error}`);
      else {
        done++;
        sent += r.bytes;
        process.stdout.write(`\r  uploaded ${done}/${sources.length}  ${mb(sent)}    `);
      }
    }

    console.log(`\n\n${done} uploaded, ${failures.length} failed`);
    for (const f of failures) console.log(`  FAIL  ${f}`);

    if (done > 0) {
      console.log("\nAdd these to .env, then rebuild:\n");
      console.log(
        `  NEXT_PUBLIC_MEDIA_IMAGE_BASE="https://res.cloudinary.com/${CLOUD}/image/upload/${FOLDER}"`,
      );
      console.log(
        `  NEXT_PUBLIC_MEDIA_VIDEO_BASE="https://res.cloudinary.com/${CLOUD}/video/upload/${FOLDER}"`,
      );
      console.log("\nThen verify: node scripts/upload-media.mjs --check\n");
    }
    if (failures.length) process.exitCode = 1;
  }
}
